# Continuous Integration

trigger:
  branches:
    include:
      - main
      - publish-perf
      # For patch releases
      - release/*
  paths:
    exclude:
      - packages/http-client-csharp

pr: none

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    BinSkimSettings:
      analyzeTargetGlob: +:file|*.exe;-:f|**/tsp.exe # Flag issue with node binary which we can't fix https://github.com/nodejs/node/issues/42100
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self

    stages:
      - stage: build
        dependsOn: []
        displayName: Build

        jobs:
          - template: /eng/tsp-core/pipelines/jobs/build-packages.yml@self
          - template: /eng/tsp-core/pipelines/jobs/build-vs.yml@self
          - template: /eng/tsp-core/pipelines/jobs/cli/build-tsp-cli-all.yml@self
          - template: /eng/tsp-core/pipelines/jobs/e2e.yml@self
            parameters:
              azLogin: true

      - stage: publish_npm
        displayName: Publish Npm Packages
        dependsOn: build

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        jobs:
          - template: /eng/tsp-core/pipelines/jobs/publish-npm.yml
            parameters:
              artifactName: npm-packages-stable
              tag: latest
              publishGithubRelease: true

          - template: /eng/tsp-core/pipelines/jobs/publish-npm.yml
            parameters:
              artifactName: npm-packages-next
              tag: next

      - stage: publish_vscode
        displayName: Publish VSCode extension
        dependsOn: build
        jobs:
          - template: /eng/tsp-core/pipelines/jobs/publish-vscode.yml

      - stage: publish_vs
        displayName: Publish VS extension
        dependsOn: build
        jobs:
          - template: /eng/tsp-core/pipelines/jobs/publish-vs.yml

      - template: /eng/tsp-core/pipelines/stages/sign-publish-tsp-cli.yml@self

      - stage: docker
        displayName: Docker
        dependsOn: []
        jobs:
          - job: docker
            displayName: Build and publish
            variables:
              imageName: "azsdkengsys.azurecr.io/typespec"
            pool:
              name: $(LINUXPOOL)
              image: $(LINUXVMIMAGE)
              os: linux
            steps:
              - task: Docker@1
                displayName: login
                inputs:
                  azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
                  azureContainerRegistry: azsdkengsys.azurecr.io
                  command: login

              - script: |
                  docker build -f ./docker/Dockerfile \
                    -t $(imageName):latest \
                    .
                displayName: "Build"
              - script: docker push $(imageName) --all-tags
                displayName: "Push"
